"""RAG package for Agent Kernel."""

from kernel_rag.chunking import (
    DEFAULT_CHUNK_OVERLAP_CHARS,
    DEFAULT_CHUNK_SIZE_CHARS,
    ChunkingError,
    DocumentChunkingService,
    DocumentNotChunkableError,
    TextChunk,
    TextChunker,
)
from kernel_rag.embeddings import (
    MOCK_EMBEDDING_DIMENSIONS,
    MOCK_EMBEDDING_MODEL,
    DocumentIndexingError,
    DocumentIndexingService,
    DocumentNotIndexableError,
    EmbeddingIndexResult,
    EmbeddingProvider,
    MockEmbeddingProvider,
)
from kernel_rag.ingestion import (
    DocumentIngestionError,
    DocumentIngestionService,
    DocumentNotFoundError,
    DocumentNotReadyError,
)
from kernel_rag.object_store import (
    DEFAULT_MAX_OBJECT_BYTES,
    DEFAULT_OBJECT_STORE_ROOT,
    LOCAL_OBJECT_URI_PREFIX,
    OBJECT_STORE_ROOT_ENV,
    LocalObjectStore,
    ObjectStoreError,
    ObjectTooLargeError,
    StoredObject,
    key_from_local_uri,
)
from kernel_rag.parsers import (
    ParsedDocument,
    ParserError,
    TextMarkdownParser,
    UnsupportedDocumentError,
)
from kernel_rag.retrieval import (
    Citation,
    CitationBuilder,
    KnowledgeBaseNotFoundError,
    RetrievalError,
    RetrievalResponse,
    RetrievalResult,
    Retriever,
)

__all__ = [
    "DEFAULT_MAX_OBJECT_BYTES",
    "DEFAULT_OBJECT_STORE_ROOT",
    "DEFAULT_CHUNK_OVERLAP_CHARS",
    "DEFAULT_CHUNK_SIZE_CHARS",
    "LOCAL_OBJECT_URI_PREFIX",
    "OBJECT_STORE_ROOT_ENV",
    "ChunkingError",
    "Citation",
    "CitationBuilder",
    "DocumentIngestionError",
    "DocumentIngestionService",
    "DocumentIndexingError",
    "DocumentIndexingService",
    "DocumentChunkingService",
    "DocumentNotFoundError",
    "DocumentNotIndexableError",
    "DocumentNotChunkableError",
    "DocumentNotReadyError",
    "EmbeddingIndexResult",
    "EmbeddingProvider",
    "KnowledgeBaseNotFoundError",
    "LocalObjectStore",
    "MOCK_EMBEDDING_DIMENSIONS",
    "MOCK_EMBEDDING_MODEL",
    "MockEmbeddingProvider",
    "ObjectStoreError",
    "ObjectTooLargeError",
    "ParsedDocument",
    "ParserError",
    "RetrievalError",
    "RetrievalResponse",
    "RetrievalResult",
    "Retriever",
    "StoredObject",
    "TextChunk",
    "TextChunker",
    "TextMarkdownParser",
    "UnsupportedDocumentError",
    "key_from_local_uri",
]
