"""Observability primitives for Agent Kernel."""

from kernel_observability.logging import (
    JsonLogFormatter,
    build_log_fields,
    build_log_record,
    log_event,
    redact_log_fields,
)
from kernel_observability.metrics import (
    InMemoryMetricsRecorder,
    MetricPoint,
    MetricsRecorder,
    NoOpMetricsRecorder,
    normalize_labels,
)
from kernel_observability.otel import (
    DEFAULT_OTEL_ENDPOINT,
    DEFAULT_OTEL_EXPORTER,
    DEFAULT_OTEL_SERVICE_NAME,
    OTEL_ENABLED_ENV,
    OTEL_ENDPOINT_ENV,
    OTEL_EXPORTER_ENV,
    OTEL_SERVICE_NAME_ENV,
    OTEL_TRACES_ENDPOINT_ENV,
    SUPPORTED_OTEL_EXPORTERS,
    OpenTelemetryConfig,
    OpenTelemetryConfigurationError,
    OpenTelemetryConfigurationResult,
    configure_opentelemetry,
    load_otel_config,
)
from kernel_observability.timing import LatencyTimer
from kernel_observability.tracing import (
    SPAN_ID_PATTERN,
    TRACE_ID_PATTERN,
    ObservabilityContext,
    create_span_id,
    create_trace_id,
    ensure_span_id,
    ensure_trace_id,
)

__all__ = [
    "SPAN_ID_PATTERN",
    "TRACE_ID_PATTERN",
    "DEFAULT_OTEL_ENDPOINT",
    "DEFAULT_OTEL_EXPORTER",
    "DEFAULT_OTEL_SERVICE_NAME",
    "ObservabilityContext",
    "JsonLogFormatter",
    "InMemoryMetricsRecorder",
    "LatencyTimer",
    "MetricPoint",
    "MetricsRecorder",
    "NoOpMetricsRecorder",
    "OTEL_ENABLED_ENV",
    "OTEL_ENDPOINT_ENV",
    "OTEL_EXPORTER_ENV",
    "OTEL_SERVICE_NAME_ENV",
    "OTEL_TRACES_ENDPOINT_ENV",
    "OpenTelemetryConfig",
    "OpenTelemetryConfigurationError",
    "OpenTelemetryConfigurationResult",
    "SUPPORTED_OTEL_EXPORTERS",
    "build_log_fields",
    "build_log_record",
    "configure_opentelemetry",
    "create_span_id",
    "create_trace_id",
    "ensure_span_id",
    "ensure_trace_id",
    "load_otel_config",
    "log_event",
    "normalize_labels",
    "redact_log_fields",
]
